package igye.springhibernate.model;

import javax.persistence.*;

@Entity(name = "MessageAID")
@Table(name = "MessageAID")
public class MessageWithAutoGeneratedId {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String text;

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Long getId() {
        return id;
    }
}